const KEY = 'WITHDRAWAL_SCENE';
const ADD_WITHDRAWAL_KEY = 'ADD_WITHDRAWAL_BENEFICIARY_ACCOUNT_SCENE';

module.exports = {
    BUTTON_ADD_NEW_BENEFICIARY: `${KEY}-BUTTON-ADD_NEW_BENEFICIARY`,
    TOUCHABLE_BENEFICIARY_ACCOUNT: `${KEY}-TOUCHABLE-BENEFICIARY_ACCOUNT`,
    TEXT_AMOUNT_LABEL: `${KEY}-TEXT-AMOUNT_LABEL`,
    TEXT_INPUT_AMOUNT: `${KEY}-TEXT_INPUT-AMOUNT`,
    BUTTON_WITHDRAWAL: `${KEY}-BUTTON-WITHDRAWAL`,

    TOUCHABLE_BANK_ITEM: `${ADD_WITHDRAWAL_KEY}-TOUCHABLE-BANK_ITEM`,
    TEXT_INPUT_BENEFICIARY_ACCOUNT: `${ADD_WITHDRAWAL_KEY}-TEXT_INPUT-BENEFICIARY_ACCOUNT`,
    BUTTON_ADD_BENEFICIARY_ACCOUNT: `${ADD_WITHDRAWAL_KEY}-BUTTON-ADD_BENEFICIARY_ACCOUNT`,
};