const KEY = 'SNACKBAR';
module.exports = {
    SNACKBAR_BUTTON_TITLE: `${KEY}-BUTTON-TITLE`,
    SNACKBAR_TEXT: `${KEY}-TEXT`,
    SNACKBAR_VIEW: `${KEY}-VIEW`,
    SNACKBAR_BUTTON_CLOSE: `${KEY}-BUTTON-CLOSE`,
    SNACKBAR_BUTTON_TEXT: `${KEY}-BUTTON-TEXT`,
};
